#!/bin/bash
#
# ShopHosting.io Webapp Load Balancing Setup
#
# This script helps configure nginx and systemd for running multiple
# webapp instances with load balancing.
#
# Usage:
#   ./setup-load-balancing.sh [instances]    - Default: 2 instances
#   ./setup-load-balancing.sh 3              - Run 3 instances
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

NUM_INSTANCES="${1:-2}"

if [[ ! "$NUM_INSTANCES" =~ ^[0-9]+$ ]] || [[ "$NUM_INSTANCES" -lt 1 ]] || [[ "$NUM_INSTANCES" -gt 9 ]]; then
    log_error "Number of instances must be between 1 and 9"
    exit 1
fi

log_info "Setting up load balancing with $NUM_INSTANCES webapp instances..."

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root (sudo)"
    exit 1
fi

# Step 1: Install the template service
log_info "Installing systemd template service..."
cp "$PROJECT_DIR/shophosting-webapp@.service" /etc/systemd/system/
systemctl daemon-reload

# Step 2: Generate upstream configuration
log_info "Generating nginx upstream configuration..."

UPSTREAM_CONF="/opt/shophosting/configs/nginx/shophosting-upstream.conf"
cat > "$UPSTREAM_CONF" << EOF
# ShopHosting.io Upstream Load Balancing Configuration
# Auto-generated by setup-load-balancing.sh
# Configured for $NUM_INSTANCES instances

upstream shophosting_app {
    least_conn;

EOF

for ((i=0; i<NUM_INSTANCES; i++)); do
    echo "    server 127.0.0.1:500$i;" >> "$UPSTREAM_CONF"
done

cat >> "$UPSTREAM_CONF" << EOF

    keepalive 32;
}
EOF

log_info "Upstream configuration written to: $UPSTREAM_CONF"

# Step 3: Check if nginx config includes our upstream
NGINX_CONF="/etc/nginx/sites-available/shophosting"
if [[ -f "$NGINX_CONF" ]]; then
    if ! grep -q "include.*shophosting-upstream.conf" /etc/nginx/nginx.conf 2>/dev/null; then
        log_warn "Add to /etc/nginx/nginx.conf in the http {} block:"
        log_warn "  include /opt/shophosting/configs/nginx/shophosting-upstream.conf;"
    fi

    if grep -q "proxy_pass http://127.0.0.1:5000" "$NGINX_CONF"; then
        log_warn "Update $NGINX_CONF:"
        log_warn "  Change: proxy_pass http://127.0.0.1:5000;"
        log_warn "  To:     proxy_pass http://shophosting_app;"
        log_warn "  Also add: proxy_http_version 1.1;"
        log_warn "  And add:  proxy_set_header Connection \"\";"
    fi
fi

# Step 4: Stop any existing single service
if systemctl is-active --quiet shophosting-webapp.service 2>/dev/null; then
    log_info "Stopping existing single-instance service..."
    systemctl stop shophosting-webapp.service
    systemctl disable shophosting-webapp.service
fi

# Step 5: Enable and start the instances
log_info "Enabling and starting $NUM_INSTANCES webapp instances..."

for ((i=0; i<NUM_INSTANCES; i++)); do
    log_info "  Starting shophosting-webapp@$i.service (port 500$i)..."
    systemctl enable "shophosting-webapp@$i.service"
    systemctl start "shophosting-webapp@$i.service"
done

# Wait for services to start
sleep 3

# Step 6: Verify
log_info "Verifying instances are running..."
ALL_RUNNING=true

for ((i=0; i<NUM_INSTANCES; i++)); do
    if systemctl is-active --quiet "shophosting-webapp@$i.service"; then
        echo -e "  ${GREEN}✓${NC} shophosting-webapp@$i.service is running on port 500$i"
    else
        echo -e "  ${RED}✗${NC} shophosting-webapp@$i.service is NOT running"
        ALL_RUNNING=false
    fi
done

echo ""
log_info "Load balancing setup complete!"
echo ""
echo "Services running:"
for ((i=0; i<NUM_INSTANCES; i++)); do
    echo "  - shophosting-webapp@$i.service on port 500$i"
done
echo ""

if [[ "$ALL_RUNNING" == "true" ]]; then
    echo "Next steps:"
    echo "  1. Add to /etc/nginx/nginx.conf (in http {} block):"
    echo "       include /opt/shophosting/configs/nginx/shophosting-upstream.conf;"
    echo ""
    echo "  2. Update /etc/nginx/sites-available/shophosting:"
    echo "       Replace:  proxy_pass http://127.0.0.1:5000;"
    echo "       With:     proxy_pass http://shophosting_app;"
    echo "                 proxy_http_version 1.1;"
    echo "                 proxy_set_header Connection \"\";"
    echo ""
    echo "  3. Test nginx config: nginx -t"
    echo "  4. Reload nginx: systemctl reload nginx"
    echo ""
    echo "To check status: systemctl status 'shophosting-webapp@*'"
    echo "To restart all: systemctl restart 'shophosting-webapp@*.service'"
else
    log_error "Some instances failed to start. Check logs with:"
    log_error "  journalctl -u shophosting-webapp@N.service -f"
fi
